### ISSUE TITLE
Ribbon layout menu crashes

### ISSUE THREAD

**Issue by SpeeQz1** [APEbbers/FreeCAD-Ribbon#111]
When attempting to open the Customize... -> Ribbon layout it would crash and give the following error:

```sh
21:52:34  "Empty widget item in QGridLayout 'gridLayout_8'."
21:52:34  Uncaught exception:
   File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./FCBinding.py", line 704, in loadDesignMenu
    LoadDesign_Ribbon.main()
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./LoadDesign_Ribbon.py", line 2552, in main
    Dialog = LoadDialog().form
             ^^^^^^^^^^^^
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./LoadDesign_Ribbon.py", line 242, in __init__
    MenuName = CommandInfoCorrections("menuText").replace("&", "")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./Standard_Functions_RIbbon.py", line 518, in CommandInfoCorrections
    CommandInfo = Command.getInfo()
                  ^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'getInfo'
Traceback (most recent call last):
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./FCBinding.py", line 704, in loadDesignMenu
    LoadDesign_Ribbon.main()
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./LoadDesign_Ribbon.py", line 2552, in main
    Dialog = LoadDialog().form
             ^^^^^^^^^^^^
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./LoadDesign_Ribbon.py", line 242, in __init__
    MenuName = CommandInfoCorrections("menuText").replace("&", "")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/FreeCAD/Mod/FreeCAD-Ribbon-Develop/./Standard_Functions_RIbbon.py", line 518, in CommandInfoCorrections
    CommandInfo = Command.getInfo()
                  ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'getInfo'
```

Usually before it may give an error or two but it would open and it would function normally without issues.

Also the `Create Sketch` button is missing from Part Design.

![image](https://github.com/user-attachments/assets/c83db074-4f1a-4c4a-a49e-a1ad039c659a)

```
OS: Linux Mint 22 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Fusion
Installed mods: 
  * fasteners 0.5.29 (Disabled)
  * lattice2 1.0.0
  * Manipulator 1.5.7
  * CurvedShapes 1.0.13
  * FreeCAD-Ribbon-Develop 1.4.0
  * SearchBar 1.0.2
  * Backups
  * OpenTheme 2024.9.1
```

**Comment by APEbbers** [comment]
Yes, i'm currently working on that part of the script. it's in progress

**Comment by SpeeQz1** [comment]
What about the missing "Create Sketch" button?

**Comment by APEbbers** [comment]
That's actually what i'm working on! In FC, the commanddata for the sketch button and the datum button have the same data. I'm now implementing a function to correct command data

**Comment by APEbbers** [comment]
It should be fixed now.
![image](https://github.com/user-attachments/assets/052b7675-25f0-4c99-82d2-d5badf1cb90f)

**Comment by SpeeQz1** [comment]
> It should be fixed now. ![image](https://private-user-images.githubusercontent.com/10145631/387379278-052b7675-25f0-4c99-82d2-d5badf1cb90f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NjI4OTksIm5iZiI6MTczMTk2MjU5OSwicGF0aCI6Ii8xMDE0NTYzMS8zODczNzkyNzgtMDUyYjc2NzUtMjVmMC00Yzk5LTgyZDItZDViYWRmMWNiOTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDIwNDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YzgyZDc3ZWZkNTQzZjFiMDc2N2Y0ZjBiMjQxZDNlNjVkOWY3YjQyYTNkYmFmOGZhZDgyM2NiMjQxZGUxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pc6l0dn7I_IXTE_aZftdS5vPDwkvKwjJxP8O9KyoNec)

Still not getting it to appear. Removed the config files and also the addon from the `Mod` folder but no changes.

![image](https://github.com/user-attachments/assets/f0ed63f6-7dd0-4c21-89af-bdae4d730e63)

**Comment by APEbbers** [comment]
The standard config file had an still error:
![image](https://github.com/user-attachments/assets/a69fbae9-162e-45b7-a08f-4e3284c1c490)
 is changed to:
![image](https://github.com/user-attachments/assets/28ffb04e-7d62-45ac-85b2-65217ea0096c)

**Comment by SpeeQz1** [comment]
And it appears to be fixed.

![image](https://github.com/user-attachments/assets/8e7adf0a-9faf-4c8f-bb5f-b1a9c5de8751)
